util-pkgs:
  pkg.installed:
    - names:
      - git
      - wget
      - unzip
      - htop
      - vim
      - make
      - build-essential
      - libssl-dev
      - zlib1g-dev
      - libbz2-dev
      - libreadline-dev
      - libsqlite3-dev
      - curl
      - llvm
      - libncurses5-dev
      - libncursesw5-dev
      - xz-utils
      - tk-dev
      - libffi-dev
      - liblzma-dev
      - python-openssl
      - python3.6-dev
      - python3-pip
      - python-dev
