# Pex build environment
require 'fileutils'

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'

WORKDIR = "~/work"
MDIR = "~/m"
SALTDIR = File.join(File.dirname(__FILE__), "salt/roots/")

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.hostname = "pexbuild"
  config.vm.network "private_network", ip: "192.168.89.6"
  config.vm.network :forwarded_port, guest: 2223, host: 2333

  if File.directory?(File.expand_path("#{WORKDIR}"))
    config.vm.synced_folder "#{WORKDIR}", "/opt/work/",
      owner: "root", group: "root"
  end

  if File.directory?(File.expand_path("#{MDIR}"))
    config.vm.synced_folder "#{MDIR}", "/opt/m",
      owner: "root", group: "root"
  end

  if File.directory?(File.expand_path("#{SALTDIR}"))
    config.vm.synced_folder "#{SALTDIR}", "/srv/"
  end
  
  config.vm.provision :salt do |salt|
      salt.masterless = true
      salt.minion_config = "salt/minion"
      salt.run_highstate = true
      salt.colorize = true
      salt.log_level = "info"
      salt.verbose = true
  end
  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "1024"]
    vb.customize ["modifyvm", :id, "--cpus", 2]
    # Disable ubuntu cloudimg console log
    vb.customize [ "modifyvm", :id, "--uartmode1", "disconnected" ]
  end
end
