Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.hostname = "pexbuild"
  config.vm.network "private_network", ip: "192.168.89.6"
  config.vm.network :forwarded_port, guest: 2222, host: 2233

  config.vm.synced_folder "/Users/mariuss/work/", "/opt/work/", owner: "root", group: "root"
  config.vm.synced_folder "salt/roots/", "/srv/"
  
  config.vm.provision :salt do |salt|
      salt.masterless = true
      salt.minion_config = "salt/minion"
      salt.run_highstate = true
      salt.colorize = true
      salt.log_level = "info"
      salt.verbose = true
  end
  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "1024"]
    vb.customize ["modifyvm", :id, "--cpus", 2]
    # Disable ubuntu cloudimg console log
    vb.customize [ "modifyvm", :id, "--uartmode1", "disconnected" ]
  end
end
